import type {
  Node,
  Program,
  NumberLiteral,
  StringLiteral,
  BooleanLiteral,
  NoneLiteral,
  Identifier,
  BinaryExpr,
  UnaryExpr,
  CallExpr,
  IndexExpr,
  MemberExpr,
  FunctionExpr,
  FunctionDecl,
  LetDecl,
  IfExpr,
  MatchExpr,
  MatchArm,
  RecordLiteral,
  ListLiteral,
  TupleLiteral,
  PipeExpr,
  BlockExpr,
  ReturnExpr,
  AwaitExpr,
  ImportStmt,
  TypeDecl,
  TypeclassDecl,
  InstanceDecl,
  Param,
  Pattern,
  ForExpr,
  WhileExpr,
  BreakExpr,
  ContinueExpr,
  ListComprehension,
  StringInterpolation,
} from './ast.js';

// Runtime import will be generated dynamically based on output location
const RUNTIME_IMPORT = (relativePath: string) => 
  `import { createADT, print } from '${relativePath}';`;

export class Transpiler {
  private output = '';
  private indent = 0;
  private inAsync = false;
  private constructors: Map<string, string> = new Map();
  private importsUsed: Set<string> = new Set();
  private typeclasses: Map<string, TypeclassDecl> = new Map();
  private instances: Map<string, InstanceDecl[]> = new Map();
  private instanceIds: Map<string, string[]> = new Map(); // Maps typeclass name to array of instance variable names
  private instanceTypes: Map<string, string[]> = new Map(); // Maps instance var name to its type checks
  private functions: Map<string, number> = new Map();
  private exports: string[] = [];
  private esmImports: string[] = [];
  private currentFilePath: string = '';
  private importedNames: Map<string, string> = new Map();
  private moduleInfoMap: Map<string, { exports: string[]; imports: string[] }> = new Map();
  private needsRuntime = false;
  private outputDir: string = '';
  private autoRunMain = false;
  private variantFieldNames: Map<string, string[]> = new Map();
  private instanceCounter = 0;

  setOutputDir(dir: string): void {
    this.outputDir = dir;
  }

  setAutoRunMain(auto: boolean): void {
    this.autoRunMain = auto;
  }

  transpile(ast: Program, filePath: string = ''): string {
    this.output = '';
    this.indent = 0;
    this.importsUsed.clear();
    this.functions.clear();
    this.exports = [];
    this.esmImports = [];
    this.importedNames.clear();
    this.instances.clear();
    this.instanceIds.clear();
    this.instanceTypes.clear();
    this.instanceCounter = 0;
    this.currentFilePath = filePath;
    this.needsRuntime = false;

    // First pass: register all typeclasses and instances for default implementations
    for (const node of ast.body) {
      if (node.type === 'TypeclassDecl') {
        const tc = node as TypeclassDecl;
        this.typeclasses.set(tc.name, tc);
      }
      if (node.type === 'InstanceDecl') {
        const inst = node as InstanceDecl;
        if (!this.instances.has(inst.typeclass)) {
          this.instances.set(inst.typeclass, []);
        }
        this.instances.get(inst.typeclass)!.push(inst);
      }
    }

    this.writeln('// Generated by Arix');
    this.writeln('');

    // First: transpile typeclasses and instances
    for (const node of ast.body) {
      if (node.type === 'TypeclassDecl' || node.type === 'InstanceDecl') {
        this.transpileNode(node);
      }
    }

    // Second: generate dispatch functions
    this.generateDispatchFunctions();

    // Third: transpile everything else
    for (const node of ast.body) {
      if (node.type !== 'TypeclassDecl' && node.type !== 'InstanceDecl') {
        this.transpileNode(node);
      }
    }

    // Add ESM imports at the top (including runtime import if needed)
    let topImports: string[] = [];
    
    if (this.needsRuntime) {
      topImports.push(RUNTIME_IMPORT('./arix-runtime.js'));
    }
    
    topImports.push(...this.esmImports);
    
    if (topImports.length > 0) {
      this.output = topImports.join('\n') + '\n\n' + this.output;
    }

    // Add exports at the bottom for functions/types
    if (this.exports.length > 0) {
      this.output = this.output.trimEnd() + '\n\nexport { ' + this.exports.join(', ') + ' };\n';
    }

    // Add auto-run main() if enabled (must be after exports)
    // Auto-run if: autoRunMain is true AND main is either exported OR just exists
    if (this.autoRunMain && (this.exports.includes('main') || this.functions.has('main'))) {
      this.output = this.output.trimEnd() + '\n\nif (typeof window === "undefined" && typeof process !== "undefined") {\n  main();\n}\n';
    }

    return this.output;
  }

  getImports(): string[] {
    return Array.from(this.importsUsed);
  }

  getExports(): string[] {
    return this.exports;
  }

  setModuleInfo(map: Map<string, { exports: string[]; imports: string[] }>): void {
    this.moduleInfoMap = map;
  }

  private writeln(text = ''): void {
    if (text === '') {
      this.output += '\n';
    } else {
      this.output += '  '.repeat(this.indent) + text + '\n';
    }
  }

  private transpileNode(node: Node): void {
    switch (node.type) {
      case 'FunctionDecl':
        this.transpileFunctionDecl(node as FunctionDecl);
        break;
      case 'LetDecl':
        this.transpileLetDecl(node as LetDecl);
        break;
      case 'TypeDecl':
        this.transpileTypeDecl(node as TypeDecl);
        break;
      case 'TypeclassDecl':
        this.transpileTypeclassDecl(node as TypeclassDecl);
        break;
      case 'InstanceDecl':
        this.transpileInstanceDecl(node as InstanceDecl);
        break;
      case 'ImportStmt':
        this.transpileImportStmt(node as ImportStmt);
        break;
      case 'CallExpr':
      case 'PipeExpr':
      case 'BinaryExpr':
      case 'MemberExpr':
      case 'IndexExpr':
      case 'UnaryExpr':
      case 'MatchExpr':
        this.writeln(this.transpileExpr(node) + ';');
        break;
      default:
        this.transpileExpr(node);
        this.writeln(';');
    }
  }

  private transpileFunctionDecl(node: FunctionDecl): void {
    this.functions.set(node.name, node.params.length);
    
    const asyncPrefix = node.isAsync ? 'async ' : '';
    const visibility = node.visibility === 'public' ? 'export ' : '';
    
    // Check if it's an operator function (body is arrow function)
    if (node.body.type === 'FunctionExpr') {
      // It's an operator function like: fn add = (+)
      const fnExpr = node.body as FunctionExpr;
      const params = fnExpr.params.map(p => p.name).join(', ');
      const body = this.transpileExpr(fnExpr.body);
      this.writeln(`${visibility}const ${node.name} = (${params}) => ${body};`);
    } else if (node.params.length === 0) {
      this.writeln(`${visibility}${asyncPrefix}function ${node.name}() {`);
      this.indent++;
      
      if (node.body.type === 'BlockExpr') {
        const block = node.body as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        if (last) {
          const lastExpr = this.transpileExpr(last);
          this.writeln(`return ${lastExpr};`);
        }
      } else {
        const body = this.transpileExpr(node.body);
        this.writeln(`return ${body};`);
      }
      
      this.indent--;
      this.writeln('}');
    } else {
      const params = node.params.map(p => p.name).join(', ');
      this.writeln(`${visibility}${asyncPrefix}function ${node.name}(${params}) {`);
      this.indent++;
      
      if (node.body.type === 'BlockExpr') {
        const block = node.body as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        if (last) {
          const lastExpr = this.transpileExpr(last);
          this.writeln(`return ${lastExpr};`);
        }
      } else {
        const body = this.transpileExpr(node.body);
        this.writeln(`return ${body};`);
      }
      
      this.indent--;
      this.writeln('}');
    }
    this.writeln();
  }

  private transpileLetDecl(node: LetDecl): void {
    const keyword = node.isMutable ? 'let' : 'const';
    const pattern = this.transpileLetPattern(node.pattern);
    const value = this.transpileExpr(node.value);
    this.writeln(`${keyword} ${pattern} = ${value};`);
  }

  private transpileLetPattern(pattern: Pattern): string {
    switch (pattern.type) {
      case 'WildcardPattern':
        return '_';
      case 'IdentifierPattern':
        return pattern.as || pattern.name;
      case 'LiteralPattern':
        return this.transpileExpr(pattern.literal);
      case 'RecordPattern':
        return `{ ${pattern.fields.map(f => {
          const varName = f.pattern.type === 'IdentifierPattern' 
            ? (f.pattern as any).as || f.pattern.name 
            : this.transpileLetPattern(f.pattern);
          const defaultPart = f.defaultValue ? ` ?? ${this.transpileExpr(f.defaultValue)}` : '';
          return `${f.key}: ${varName}${defaultPart}`;
        }).join(', ')} }`;
      case 'TuplePattern':
        return `[${pattern.elements.map(e => this.transpileLetPattern(e)).join(', ')}]`;
      case 'ListPattern': {
        const elements = pattern.elements.map(e => this.transpileLetPattern(e)).join(', ');
        const rest = pattern.rest ? `, ...${pattern.rest}` : '';
        return `[${elements}${rest}]`;
      }
      case 'ConstructorPattern':
        const args = pattern.patterns.map(p => this.transpileLetPattern(p)).join(', ');
        return `${pattern.name}(${args})`;
      default:
        return '_';
    }
  }

  private transpilePattern(pattern: Pattern): string {
    switch (pattern.type) {
      case 'WildcardPattern':
        return '_';
      case 'IdentifierPattern':
        return pattern.as || pattern.name;
      case 'LiteralPattern':
        return this.transpileExpr(pattern.literal);
      case 'RecordPattern':
        return `{ ${pattern.fields.map(f => {
          const value = this.transpilePattern(f.pattern);
          return `${f.key}: ${value}`;
        }).join(', ')} }`;
      case 'TuplePattern':
        return `[${pattern.elements.map(e => this.transpilePattern(e)).join(', ')}]`;
      case 'ListPattern':
        return `[${pattern.elements.map(e => this.transpilePattern(e)).join(', ')}]`;
      case 'ConstructorPattern':
        const args = pattern.patterns.map(p => this.transpilePattern(p)).join(', ');
        return `${pattern.name}(${args})`;
      default:
        return '_';
    }
  }

  private transpileTypeDecl(node: TypeDecl): void {
    this.exports.push(node.name);
    
    if (node.recordFields) {
      const fields = node.recordFields.map(f => {
        const defaultPart = f.default ? ` = ${this.transpileExpr(f.default)}` : '';
        return `${f.name}: ${this.transpileType(f.fieldType)}${defaultPart}`;
      }).join(', ');
      this.writeln(`const ${node.name} = { ${fields} };`);
    } else {
      this.needsRuntime = true;
      
      const variants: Record<string, string[]> = {};
      for (const variant of node.variants) {
        const fieldNames = variant.fields.map(f => f.name);
        variants[variant.name] = fieldNames;
        this.constructors.set(variant.name, `${node.name}.${variant.name}`);
        this.variantFieldNames.set(variant.name, fieldNames);
        this.exports.push(variant.name);
      }
      
      const variantsStr = JSON.stringify(variants)
        .replace(/"/g, "'")
        .replace(/'([^']+)':/g, '$1:');
      
      this.writeln(`const ${node.name} = createADT('${node.name}', ${variantsStr});`);
      
      for (const variant of node.variants) {
        this.writeln(`const ${variant.name} = ${node.name}.${variant.name};`);
      }
    }
    this.writeln();
  }

  private transpileType(node: Node): string {
    if (node.type === 'Identifier') {
      return (node as Identifier).name;
    }
    if (node.type === 'CallExpr') {
      const call = node as CallExpr;
      const args = call.args.map(a => this.transpileType(a)).join(', ');
      return `${this.transpileExpr(call.callee)}<${args}>`;
    }
    return 'any';
  }

  private transpileImportStmt(node: ImportStmt): void {
    const stdlibModules = ['result', 'maybe', 'list'];
    const moduleNameLower = node.module.toLowerCase();

    if (stdlibModules.includes(moduleNameLower)) {
      const jsPath = `./${moduleNameLower}.js`;
      const moduleInfo = this.moduleInfoMap.get(node.module);

      if (moduleInfo && moduleInfo.exports.length > 0) {
        const itemsStr = moduleInfo.exports.join(', ');
        this.esmImports.push(`import { ${itemsStr} } from '${jsPath}';`);
        for (const item of moduleInfo.exports) {
          this.importedNames.set(item, '');
          this.constructors.set(item, item);
        }
      } else {
        this.esmImports.push(`import * as ${moduleNameLower} from '${jsPath}';`);
      }
      return;
    }

    this.needsRuntime = true;
    
    const jsPath = this.moduleToJsPath(node.module, node.isRelative);
    
    const moduleName = this.getModuleName(node.module);
    const alias = node.alias || moduleName;
    
    if (node.items && node.items.length > 0) {
      const itemsStr = node.items.join(', ');
      this.esmImports.push(`import { ${itemsStr} } from '${jsPath}';`);
      for (const item of node.items) {
        this.importedNames.set(item, '');
        this.constructors.set(item, item);
      }
    } else if (node.alias) {
      this.esmImports.push(`import * as ${alias} from '${jsPath}';`);
      this.importedNames.set(alias, alias);
      this.constructors.set(alias, alias);
    } else {
      this.esmImports.push(`import * as ${alias} from '${jsPath}';`);
      
      const moduleKey = node.isRelative ? node.module : this.getModuleName(node.module);
      const moduleInfo = this.moduleInfoMap.get(node.module) || this.moduleInfoMap.get(moduleKey);
      
      if (moduleInfo) {
        for (const exportedName of moduleInfo.exports) {
          this.importedNames.set(exportedName, alias);
        }
      }
    }
  }

  private getModuleName(modulePath: string): string {
    const parts = modulePath.split('/');
    return parts[parts.length - 1];
  }

  private moduleToJsPath(module: string, isRelative: boolean): string {
    if (isRelative) {
      // Relative import: ./foo-bar or ../foo-bar (module already includes ./ or ../)
      return `${module}.js`;
    } else {
      // Local import: foo-bar -> ./foo-bar.js
      return `./${module}.js`;
    }
  }

  private transpileExpr(node: Node): string {
    if (!node) {
      console.error('Error: transpileExpr called with undefined node');
      throw new Error('transpileExpr called with undefined node');
    }
    switch (node.type) {
      case 'NumberLiteral':
        return String((node as NumberLiteral).value);
      
      case 'StringLiteral':
        const str = (node as StringLiteral).value.replace(/"/g, '\\"');
        return `"${str}"`;
      
      case 'BooleanLiteral':
        return String((node as BooleanLiteral).value);
      
      case 'NoneLiteral':
        return 'null';
      
      case 'Identifier': {
        const name = (node as Identifier).name;
        const fullName = this.constructors.get(name);
        if (fullName) {
          const fieldNames = this.variantFieldNames.get(name);
          if (fieldNames && fieldNames.length === 0) {
            return `${fullName}()`;
          }
          return fullName;
        }
        
        const namespace = this.importedNames.get(name);
        if (namespace) {
          return namespace ? `${namespace}.${name}` : name;
        }
        
        return name;
      }
      
      case 'BinaryExpr': {
        const bin = node as BinaryExpr;
        const left = this.transpileExpr(bin.left);
        const right = this.transpileExpr(bin.right);
        
        if (bin.operator === '||') {
          return `(${left} || ${right})`;
        }
        if (bin.operator === '&&') {
          return `(${left} && ${right})`;
        }
        if (bin.operator === '==') {
          return `(${left} === ${right})`;
        }
        if (bin.operator === '!=') {
          return `(${left} !== ${right})`;
        }
        if (bin.operator === '++') {
          return `(${left} + ${right})`;
        }
        return `(${left} ${bin.operator} ${right})`;
      }
      
      case 'UnaryExpr': {
        const unary = node as UnaryExpr;
        const operand = this.transpileExpr(unary.operand);
        return `${unary.operator}${operand}`;
      }
      
      case 'IndexExpr': {
        const index = node as IndexExpr;
        const object = this.transpileExpr(index.object);
        const idx = this.transpileExpr(index.index);
        return `${object}.get(${idx})`;
      }
      
      case 'MemberExpr': {
        const member = node as MemberExpr;
        const object = this.transpileExpr(member.object);
        const property = (member.property as Identifier).name;
        return `${object}.${property}`;
      }
      
      case 'CallExpr': {
        const call = node as CallExpr;
        let calleeStr = this.transpileExpr(call.callee);
        
        // Detect print() usage and mark runtime as needed
        if (call.callee.type === 'Identifier') {
          const funcName = (call.callee as Identifier).name;
          if (funcName === 'print') {
            this.needsRuntime = true;
          }
        }
        
        if (call.callee.type === 'MemberExpr' && call.args.length === 0) {
          return `${calleeStr}()`;
        }
        if (call.args.length === 0) {
          return `${calleeStr}()`;
        }
        
        const args = call.args.map(a => this.transpileExpr(a)).join(', ');
        const argCount = call.args.length;
        
        // Check for currying: if calling a known function with fewer args than params
        if (call.callee.type === 'Identifier') {
          const funcName = (call.callee as Identifier).name;
          const paramCount = this.functions.get(funcName);
          if (paramCount !== undefined && argCount < paramCount) {
            // Generate curried function: (_c1) => (_c2) => fn(arg1, _c1, _c2)
            let result = '';
            for (let i = argCount; i < paramCount; i++) {
              result += `(_c${i}) => `;
            }
            result += `${calleeStr}(${args}`;
            for (let i = argCount; i < paramCount; i++) {
              result += `, _c${i}`;
            }
            result += ')';
            return result;
          }
        }
        
        // Wrap arrow functions in parentheses when called (for precedence)
        if (calleeStr.startsWith('(') && calleeStr.includes('=>')) {
          calleeStr = `(${calleeStr})`;
        }
        
        return `${calleeStr}(${args})`;
      }
      
      case 'FunctionExpr': {
        const fn = node as FunctionExpr;
        const params = fn.params.map(p => p.name).join(', ');
        const body = this.transpileExpr(fn.body);
        const getOperator = (op: string) => op === '++' ? '+' : op;
        if (fn.params.length === 1 && fn.params[0].name === '_left' && fn.body.type === 'BinaryExpr') {
          const bin = fn.body as BinaryExpr;
          if (bin.left.type === 'Identifier' && (bin.left as Identifier).name === '_left') {
            const op = getOperator(bin.operator);
            const right = this.transpileExpr(bin.right);
            return `(_left) => (_left ${op} ${right})`;
          }
          if (bin.right.type === 'Identifier' && (bin.right as Identifier).name === '_left') {
            const op = getOperator(bin.operator);
            const left = this.transpileExpr(bin.left);
            return `(_right) => (${left} ${op} _right)`;
          }
        }
        if (fn.params.length === 2 && fn.params[0].name === '_left' && fn.params[1].name === '_right' && fn.body.type === 'BinaryExpr') {
          const bin = fn.body as BinaryExpr;
          const left = this.transpileExpr(bin.left);
          const right = this.transpileExpr(bin.right);
          const op = getOperator(bin.operator);
          return `(_left, _right) => (_left ${op} _right)`;
        }
        return `(${params}) => ${body}`;
      }
      
      case 'IfExpr': {
        const ifExpr = node as IfExpr;
        const condition = this.transpileExpr(ifExpr.condition);
        const thenBranch = this.transpileExpr(ifExpr.thenBranch);
        const elseBranch = this.transpileExpr(ifExpr.elseBranch);
        return `((${condition}) ? ${thenBranch} : ${elseBranch})`;
      }
      
      case 'MatchExpr': {
        const match = node as MatchExpr;
        return this.transpileMatchExpr(match);
      }
      
      case 'RecordLiteral': {
        const record = node as RecordLiteral;
        const fields = record.fields.map(f => 
          `${f.key}: ${this.transpileExpr(f.value)}`
        ).join(', ');
        return `{ ${fields} }`;
      }
      
      case 'ListLiteral': {
        const list = node as ListLiteral;
        const elements = list.elements.map(e => this.transpileExpr(e)).join(', ');
        return `[${elements}]`;
      }
      
      case 'TupleLiteral': {
        const tuple = node as TupleLiteral;
        const elements = tuple.elements.map(e => this.transpileExpr(e)).join(', ');
        return `[${elements}]`;
      }
      
      case 'PipeExpr': {
        const pipe = node as PipeExpr;
        return this.transpilePipeExpr(pipe);
      }
      
      case 'BlockExpr': {
        const block = node as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        return this.transpileExpr(last);
      }

      case 'ReturnExpr': {
        const ret = node as ReturnExpr;
        if (ret.value) {
          return `return ${this.transpileExpr(ret.value)}`;
        }
        return 'return';
      }
      
      case 'AwaitExpr': {
        const awaitExpr = node as AwaitExpr;
        const expr = this.transpileExpr(awaitExpr.expression);
        return `await ${expr}`;
      }
      
      case 'ForExpr': {
        const forExpr = node as ForExpr;
        const pattern = this.transpilePattern(forExpr.pattern);
        const iterable = this.transpileExpr(forExpr.iterable);
        const body = this.transpileExpr(forExpr.body);
        let loopCode = `for (const ${pattern} of ${iterable}) {\n`;
        this.indent++;
        if (forExpr.condition) {
          const condition = this.transpileExpr(forExpr.condition);
          loopCode += this.getIndent() + `if (!(${condition})) continue;\n`;
        }
        loopCode += this.getIndent() + body;
        this.indent--;
        loopCode += `\n${this.getIndent()}}`;
        return loopCode;
      }
      
      case 'WhileExpr': {
        const whileExpr = node as WhileExpr;
        const condition = this.transpileExpr(whileExpr.condition);
        const body = this.transpileExpr(whileExpr.body);
        let loopCode = `while (${condition}) {\n`;
        this.indent++;
        loopCode += this.getIndent() + body;
        this.indent--;
        loopCode += `\n${this.getIndent()}}`;
        return loopCode;
      }
      
      case 'BreakExpr': {
        return 'break';
      }
      
      case 'ContinueExpr': {
        return 'continue';
      }
      
      case 'ListComprehension': {
        const comp = node as ListComprehension;
        const element = this.transpileExpr(comp.element);
        const pattern = this.transpilePattern(comp.pattern);
        const iterable = this.transpileExpr(comp.iterable);
        
        if (comp.condition) {
          const condition = this.transpileExpr(comp.condition);
          return `${iterable}.filter(${pattern} => ${condition}).map(${pattern} => ${element})`;
        }
        
        return `${iterable}.map(${pattern} => ${element})`;
      }
      
      case 'StringInterpolation': {
        const interp = node as StringInterpolation;
        let result = '`';
        for (const part of interp.parts) {
          if (part.type === 'StringPart') {
            result += (part as any).value;
          } else if (part.type === 'ExprPart') {
            const expr = this.transpileExpr((part as any).expr);
            result += `\${${expr}}`;
          }
        }
        result += '`';
        return result;
      }
      
      default:
        return 'undefined';
    }
  }

  private transpileMatchExpr(match: MatchExpr): string {
    const value = this.transpileExpr(match.value);
    const cases = match.arms.map(arm => {
      const { bindings, condition, refs } = this.transpileMatchPattern(arm.pattern);
      const body = this.transpileExpr(arm.body);
      let guardCondition = condition;
      if (arm.guard) {
        const guard = this.transpileExpr(arm.guard.condition);
        guardCondition = guardCondition ? `(${guardCondition} && ${guard})` : guard;
      }
      return { bindings, condition: guardCondition, body, refs };
    });

    let result = `((__v) => {\n`;
    for (const c of cases) {
      let refs = c.refs;
      if (refs.endsWith('; ')) refs = refs.slice(0, -2);
      else if (refs.endsWith(';')) refs = refs.slice(0, -1);
      const allBindings = [refs, c.bindings].filter(b => b).join('; ');
      if (c.condition) {
        result += `  { ${allBindings}${allBindings ? '; ' : ''}if (${c.condition}) { return ${c.body}; } }\n`;
      } else {
        result += `  { ${allBindings}${allBindings ? '; ' : ''}return ${c.body}; }\n`;
      }
    }
    result += `})(${value})`;
    return result;
  }

  private transpileMatchPattern(pattern: Pattern, value: string = '__v'): { bindings: string; condition: string; refs: string } {
    switch (pattern.type) {
      case 'WildcardPattern':
        return { bindings: '', condition: '', refs: '' };
      case 'IdentifierPattern':
        return { bindings: '', condition: '', refs: `const ${pattern.name} = ${value}` };
      case 'LiteralPattern':
        return { bindings: '', condition: `${value} === ${this.transpileExpr(pattern.literal)}`, refs: '' };
      case 'RecordPattern': {
        const conds: string[] = [];
        const binds: string[] = [];
        const refs: string[] = [];
        for (const f of pattern.fields) {
          const fieldValue = `${value}.${f.key}`;
          const result = this.transpileMatchPattern(f.pattern, fieldValue);
          if (result.condition) conds.push(result.condition);
          if (result.bindings) binds.push(result.bindings);
          if (result.refs) refs.push(result.refs);
        }
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join(' ') };
      }
      case 'ListPattern': {
        if (pattern.rest) {
          const { condition: elemCond, bindings: elemBind, refs: elemRefs } = this.transpileArrayHeadTail(pattern.elements, value);
          return { bindings: elemBind, condition: elemCond, refs: `const ${pattern.rest} = ${value}.slice(${pattern.elements.length}); ${elemRefs}` };
        }
        const elems = pattern.elements.map((e, i) => this.transpileMatchPattern(e, `${value}[${i}]`));
        const conds = elems.map(e => e.condition).filter(c => c);
        const binds = elems.map(e => e.bindings).filter(b => b);
        const refs = elems.map(e => e.refs).filter(r => r);
        return { bindings: binds.join(' '), condition: `${value}.length === ${pattern.elements.length}${conds.length ? ' && ' + conds.join(' && ') : ''}`, refs: refs.join(' ') };
      }
      case 'TuplePattern': {
        const elems = pattern.elements.map((e, i) => this.transpileMatchPattern(e, `${value}[${i}]`));
        const conds = elems.map(e => e.condition).filter(c => c);
        const binds = elems.map(e => e.bindings).filter(b => b);
        const refs = elems.map(e => e.refs).filter(r => r);
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join(' ') };
      }
      case 'ConstructorPattern': {
        // Always use _variant for ADT pattern matching (built-in and custom)
        const conds = [`${value}._variant === '${pattern.name}'`];
        const binds: string[] = [];
        const refs: string[] = [];
        const fieldNames = this.getVariantFieldNames(pattern.name);
        pattern.patterns.forEach((p, i) => {
          const fieldName = fieldNames[i] || `v${i}`;
          if (p.type === 'IdentifierPattern') {
            const bindName = (p as any).name;
            refs.push(`const ${bindName} = ${value}.${fieldName}`);
          } else {
            const result = this.transpileMatchPattern(p, `${value}.${fieldName}`);
            if (result.condition) conds.push(result.condition);
            if (result.bindings) binds.push(result.bindings);
            if (result.refs) refs.push(result.refs);
          }
        });
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join('; ') };
      }
      default:
        return { bindings: '', condition: '', refs: '' };
    }
  }

  private transpileArrayHeadTail(patterns: Pattern[], value: string): { condition: string; bindings: string; refs: string } {
    const conds: string[] = [];
    const binds: string[] = [];
    const refs: string[] = [];
    patterns.forEach((p, i) => {
      const result = this.transpileMatchPattern(p, `${value}[${i}]`);
      if (result.condition) conds.push(result.condition);
      if (result.bindings) binds.push(result.bindings);
      if (result.refs) refs.push(result.refs);
    });
    return { condition: conds.join(' && '), bindings: binds.join(' '), refs: refs.join(' ') };
  }

  private getVariantFieldNames(typeName: string): string[] {
    // Check if this is a custom ADT variant first
    if (this.variantFieldNames.has(typeName)) {
      return this.variantFieldNames.get(typeName) || [];
    }
    
    const fieldMap: Record<string, string[]> = {
      'Circle': ['r'],
      'Rectangle': ['width', 'height'],
      'Ok': ['value'],
      'Err': ['error'],
      'Some': ['value'],
      'Just': ['value'],
      'Nothing': [],
      'Cons': ['head', 'tail'],
      'Nil': [],
    };
    return fieldMap[typeName] || [];
  }

  private getIndent(): string {
    return '  '.repeat(this.indent);
  }

  private transpilePipeExpr(pipe: PipeExpr): string {
    const left = this.transpileExpr(pipe.left);
    const right = pipe.right;
    
    if (right.type === 'CallExpr') {
      const call = right as CallExpr;
      const callee = this.transpileExpr(call.callee);
      const existingArgs = call.args.map(a => this.transpileExpr(a)).join(', ');
      const args = existingArgs ? `${existingArgs}, ${left}` : left;
      return `${callee}(${args})`;
    }
    
    const rightStr = this.transpileExpr(right);
    return `${rightStr}(${left})`;
  }

  private transpileTypeclassDecl(node: TypeclassDecl): void {
    this.exports.push(node.name);
    for (const method of node.methods) {
      this.exports.push(method.name);
    }
    
    // Generate default implementations for methods with bodies
    for (const method of node.methods) {
      if (method.body) {
        // Generate a default implementation function
        const defaultFnName = `__default_${node.name}_${method.name}`;
        const paramList = method.params.map(p => p.name).join(', ');
        this.writeln(`const ${defaultFnName} = function(${paramList}) {`);
        this.indent++;
        const methodBody = this.transpileExpr(method.body);
        this.writeln(`return ${methodBody};`);
        this.indent--;
        this.writeln('};');
      }
    }
    
    // Typeclasses are just type declarations at transpile time
    // The actual method dispatch happens at runtime via the constraint registry
    // Generate a const that represents the typeclass interface
    this.writeln(`const ${node.name} = {`);
    this.indent++;
    
    for (const method of node.methods) {
      if (method.body) {
        this.writeln(`${method.name}: __default_${node.name}_${method.name},`);
      } else {
        this.writeln(`${method.name}: null, // Will be filled by instances`);
      }
    }
    
    this.indent--;
    this.writeln('};');
    this.writeln();
  }

  private transpileInstanceDecl(node: InstanceDecl): void {
    // Generate the instance implementation object
    // For Convertible for (Int, String), we generate something like:
    // registerInstance('Convertible', ['Int', 'String'], { convert: (x) => x.toString() });
    
    const forTypesStr = node.forTypes.length === 1 
      ? this.transpileExpr(node.forTypes[0])
      : `[${node.forTypes.map(t => this.transpileExpr(t)).join(', ')}]`;
    
    this.writeln(`// Instance: ${node.typeclass} for ${forTypesStr}`);
    
    // Generate a predictable instance variable name
    const instanceVarName = `__instance_${node.typeclass}_${this.instanceCounter++}`;
    
    // Store the instance variable name for later dispatch generation
    if (!this.instanceIds.has(node.typeclass)) {
      this.instanceIds.set(node.typeclass, []);
    }
    this.instanceIds.get(node.typeclass)!.push(instanceVarName);
    
    // Store type information for this instance
    const typeNames = node.forTypes.map(t => this.getTypeName(t));
    this.instanceTypes.set(instanceVarName, typeNames);
    
    // Get the typeclass to check for default implementations
    const typeclass = this.typeclasses.get(node.typeclass);
    const implementedMethods = new Set(node.methods.map(m => m.name));
    
    // Generate an object with all the methods (implementing + defaults)
    this.writeln(`const ${instanceVarName} = {`);
    this.indent++;
    
    // First, add the implemented methods
    for (const method of node.methods) {
      // Use parameter names from the implementation if available, otherwise from typeclass
      let paramList = 'x';
      if (method.params && method.params.length > 0) {
        paramList = method.params.join(', ');
      } else if (typeclass) {
        const tcMethod = typeclass.methods.find(m => m.name === method.name);
        if (tcMethod && tcMethod.params.length > 0) {
          paramList = tcMethod.params.map(p => p.name || 'arg').join(', ');
        }
      }
      
      const methodBody = this.transpileExpr(method.body);
      this.writeln(`${method.name}: function(${paramList}) { return ${methodBody}; },`);
    }
    
    // Then, add default implementations from the typeclass for methods not implemented
    if (typeclass) {
      for (const method of typeclass.methods) {
        if (!implementedMethods.has(method.name) && method.body) {
          // Use the default implementation
          this.writeln(`${method.name}: __default_${node.typeclass}_${method.name},`);
        }
      }
    }
    
    this.indent--;
    this.writeln('};');
    this.writeln();
  }

  private getTypeName(typeNode: Node | any): string {
    if (typeof typeNode === 'string') {
      return typeNode;
    }
    if (typeNode.type === 'Identifier') {
      return typeNode.name;
    }
    if (typeNode.type === 'GenericType') {
      return typeNode.name; // Return base name like 'List' from 'List(a)'
    }
    if (typeNode.type === 'CallExpr' && typeNode.callee && typeNode.callee.type === 'Identifier') {
      return typeNode.callee.name; // Return 'List' from List(a)
    }
    return 'unknown';
  }

  private generateDispatchFunctions(): void {
    // Generate dispatch functions for each typeclass method
    for (const [tcName, tc] of this.typeclasses) {
      const instanceVarNames = this.instanceIds.get(tcName) || [];
      
      if (instanceVarNames.length === 0) {
        // No instances for this typeclass - skip dispatch generation
        continue;
      }

      // For each method in the typeclass, create a dispatch function
      for (const method of tc.methods) {
        const methodName = method.name;
        
        // Extract parameter names from the method signature
        const paramNames = method.params.map(p => {
          if (p.name) return p.name;
          return 'arg';
        });
        const paramList = paramNames.join(', ');
        
        this.writeln(`// Dispatch function for ${tcName}.${methodName}`);
        this.writeln(`const ${methodName} = (${paramList}) => {`);
        this.indent++;
        
        // Try each instance in order with type checking
        for (const instanceVarName of instanceVarNames) {
          const typeNames = this.instanceTypes.get(instanceVarName) || [];
          const typeCheck = this.generateTypeCheck(typeNames[0]);
          
          this.writeln(`if (${typeCheck}) {`);
          this.indent++;
          this.writeln(`if (${instanceVarName}.${methodName}) {`);
          this.indent++;
          this.writeln(`return ${instanceVarName}.${methodName}(${paramList});`);
          this.indent--;
          this.writeln(`}`);
          this.indent--;
          this.writeln(`}`);
        }
        
        // Fallback: use default implementation if available
        if (method.body) {
          const defaultImpl = this.transpileExpr(method.body);
          this.writeln(`return ${defaultImpl};`);
        } else {
          this.writeln(`throw new Error('No instance of ${tcName} found for ' + typeof ${paramNames[0]});`);
        }
        
        this.indent--;
        this.writeln('};');
        this.writeln();
      }
    }
  }

  private generateTypeCheck(typeName: string | undefined): string {
    if (!typeName) return 'true';
    
    switch (typeName) {
      case 'Int':
        return 'Number.isInteger(x)';
      case 'String':
        return 'typeof x === "string"';
      case 'Boolean':
        return 'typeof x === "boolean"';
      case 'Float':
        return 'typeof x === "number" && !Number.isInteger(x)';
      case 'List':
        return 'Array.isArray(x)';
      default:
        return `x && x._type === '${typeName}'`;
    }
  }
}

export function transpile(ast: Program): string {
  const transpiler = new Transpiler();
  return transpiler.transpile(ast);
}
