import type {
  Node,
  Program,
  NumberLiteral,
  StringLiteral,
  BooleanLiteral,
  NoneLiteral,
  Identifier,
  BinaryExpr,
  UnaryExpr,
  CallExpr,
  IndexExpr,
  MemberExpr,
  FunctionExpr,
  FunctionDecl,
  LetDecl,
  IfExpr,
  MatchExpr,
  MatchArm,
  RecordLiteral,
  ListLiteral,
  TupleLiteral,
  PipeExpr,
  BlockExpr,
  ReturnExpr,
  AwaitExpr,
  ImportStmt,
  TypeDecl,
  TypeclassDecl,
  InstanceDecl,
  Param,
  Pattern,
  ForExpr,
  WhileExpr,
  BreakExpr,
  ContinueExpr,
  ListComprehension,
  StringInterpolation,
} from './ast.js';

// Runtime import will be generated dynamically based on output location
const RUNTIME_IMPORT = (relativePath: string) => 
  `import { createADT, print } from '${relativePath}';`;

const STDLIB_MODULES = ['result', 'maybe', 'list', 'show', 'functor', 'applicative', 'monad', 'monoid'];

interface GlobalInstanceInfo {
  typeclass: string;
  forTypes: string[];
  methods: string[];
  module: string;
}

export class Transpiler {
  private output = '';
  private indent = 0;
  private inAsync = false;
  private constructors: Map<string, string> = new Map();
  private importsUsed: Set<string> = new Set();
  private typeclasses: Map<string, TypeclassDecl> = new Map();
  private globalTypeclasses: Map<string, TypeclassDecl> = new Map();
  private instances: Map<string, InstanceDecl[]> = new Map();
  private instanceIds: Map<string, string[]> = new Map(); // Maps typeclass name to array of instance variable names
  private instanceTypes: Map<string, string[]> = new Map(); // Maps instance var name to its type checks
  private functions: Map<string, number> = new Map();
  private exports: string[] = [];
  private esmImports: string[] = [];
  private currentFilePath: string = '';
  private importedNames: Map<string, string> = new Map();
  private moduleInfoMap: Map<string, { exports: string[]; imports: string[] }> = new Map();
  private moduleNamespaces: Map<string, string> = new Map();
  private needsRuntime = false;
  private outputDir: string = '';
  private autoRunMain = false;
  private variantFieldNames: Map<string, string[]> = new Map();
  private instanceCounter = 0;
  private globalInstances: GlobalInstanceInfo[] = [];

  setOutputDir(dir: string): void {
    this.outputDir = dir;
  }

  setAutoRunMain(auto: boolean): void {
    this.autoRunMain = auto;
  }

  transpile(ast: Program, filePath: string = ''): string {
    this.output = '';
    this.indent = 0;
    this.importsUsed.clear();
    this.functions.clear();
    this.exports = [];
    this.esmImports = [];
    this.importedNames.clear();
    this.instances.clear();
    this.instanceIds.clear();
    this.instanceTypes.clear();
    this.moduleNamespaces.clear();
    this.instanceCounter = 0;
    this.currentFilePath = filePath;
    this.needsRuntime = false;

    const explicitImports = ast.body.filter((node): node is ImportStmt => node.type === 'ImportStmt');
    const implicitStdlibImports = this.getImplicitStdlibImports(explicitImports);

    // Merge global typeclasses with local ones (local takes precedence)
    this.typeclasses = new Map(this.globalTypeclasses);

    // Pre-register top-level function signatures so dispatch generation can avoid name clashes.
    for (const node of ast.body) {
      if (node.type === 'FunctionDecl') {
        const fn = node as FunctionDecl;
        this.functions.set(fn.name, fn.params.length);
      }
      if (node.type === 'ImportStmt') {
        this.registerImportNamespace(node as ImportStmt);
      }
    }

    for (const importNode of implicitStdlibImports) {
      this.registerImportNamespace(importNode);
    }

    // First pass: register all typeclasses and instances for default implementations
    let firstPassInstanceCounter = 0;
    for (const node of ast.body) {
      if (node.type === 'TypeclassDecl') {
        const tc = node as TypeclassDecl;
        this.typeclasses.set(tc.name, tc);
      }
      if (node.type === 'InstanceDecl') {
        const inst = node as InstanceDecl;
        if (!this.instances.has(inst.typeclass)) {
          this.instances.set(inst.typeclass, []);
        }
        this.instances.get(inst.typeclass)!.push(inst);
        
        // Also track instance variable names and types for dispatch generation
        if (!this.instanceIds.has(inst.typeclass)) {
          this.instanceIds.set(inst.typeclass, []);
        }
        const instanceVarName = `__instance_${inst.typeclass}_${firstPassInstanceCounter}`;
        this.instanceIds.get(inst.typeclass)!.push(instanceVarName);
        const typeNames = inst.forTypes.map(t => this.getTypeName(t));
        this.instanceTypes.set(instanceVarName, typeNames);
        firstPassInstanceCounter++;
      }
    }

    this.writeln('// Generated by Arix');
    this.writeln('');
    this.emitListHelpers();

    // First: transpile typeclasses only
    for (const node of ast.body) {
      if (node.type === 'TypeclassDecl') {
        this.transpileNode(node);
      }
    }

    // Second: generate dispatch functions (before instances, so instances can use them)
    this.generateDispatchFunctions();

    // Third: transpile instances
    for (const node of ast.body) {
      if (node.type === 'InstanceDecl') {
        this.transpileNode(node);
      }
    }

    // Fourth: transpile everything else
    for (const importNode of implicitStdlibImports) {
      this.transpileImportStmt(importNode);
    }

    for (const node of ast.body) {
      if (node.type !== 'TypeclassDecl' && node.type !== 'InstanceDecl') {
        this.transpileNode(node);
      }
    }

    // Add ESM imports at the top (including runtime import if needed)
    let topImports: string[] = [];
    
    if (this.needsRuntime) {
      topImports.push(RUNTIME_IMPORT('./arix-runtime.js'));
    }
    
    topImports.push(...this.esmImports);
    
    if (topImports.length > 0) {
      this.output = topImports.join('\n') + '\n\n' + this.output;
    }

    // Add exports at the bottom for functions/types
    if (this.exports.length > 0) {
      this.output = this.output.trimEnd() + '\n\nexport { ' + this.exports.join(', ') + ' };\n';
    }

    // Add auto-run main() if enabled (must be after exports)
    // Auto-run if: autoRunMain is true AND main is either exported OR just exists
    if (this.autoRunMain && (this.exports.includes('main') || this.functions.has('main'))) {
      this.output = this.output.trimEnd() + '\n\nif (typeof window === "undefined" && typeof process !== "undefined") {\n  main();\n}\n';
    }

    return this.output;
  }

  getImports(): string[] {
    return Array.from(this.importsUsed);
  }

  getExports(): string[] {
    return this.exports;
  }

  setModuleInfo(map: Map<string, { exports: string[]; imports: string[] }>): void {
    this.moduleInfoMap = map;
  }

  setGlobalTypeclasses(typeclasses: Map<string, TypeclassDecl>): void {
    this.globalTypeclasses = typeclasses;
  }

  setGlobalInstances(instances: GlobalInstanceInfo[]): void {
    this.globalInstances = instances;
  }

  private writeln(text = ''): void {
    if (text === '') {
      this.output += '\n';
    } else {
      this.output += '  '.repeat(this.indent) + text + '\n';
    }
  }

  private transpileNode(node: Node): void {
    switch (node.type) {
      case 'FunctionDecl':
        this.transpileFunctionDecl(node as FunctionDecl);
        break;
      case 'LetDecl':
        this.transpileLetDecl(node as LetDecl);
        break;
      case 'TypeDecl':
        this.transpileTypeDecl(node as TypeDecl);
        break;
      case 'TypeclassDecl':
        this.transpileTypeclassDecl(node as TypeclassDecl);
        break;
      case 'InstanceDecl':
        this.transpileInstanceDecl(node as InstanceDecl);
        break;
      case 'ImportStmt':
        this.transpileImportStmt(node as ImportStmt);
        break;
      case 'CallExpr':
      case 'PipeExpr':
      case 'BinaryExpr':
      case 'MemberExpr':
      case 'IndexExpr':
      case 'UnaryExpr':
      case 'MatchExpr':
        this.writeln(this.transpileExpr(node) + ';');
        break;
      default:
        this.transpileExpr(node);
        this.writeln(';');
    }
  }

  private transpileFunctionDecl(node: FunctionDecl): void {
    this.functions.set(node.name, node.params.length);
    
    const asyncPrefix = node.isAsync ? 'async ' : '';
    const visibility = node.visibility === 'public' ? 'export ' : '';
    
    // Check if it's an operator function (body is arrow function)
    if (node.body.type === 'FunctionExpr') {
      // It's an operator function like: fn add = (+)
      const fnExpr = node.body as FunctionExpr;
      const params = fnExpr.params.map(p => p.name).join(', ');
      const body = this.transpileExpr(fnExpr.body);
      this.writeln(`${visibility}const ${node.name} = (${params}) => ${body};`);
    } else if (node.params.length === 0) {
      this.writeln(`${visibility}${asyncPrefix}function ${node.name}() {`);
      this.indent++;
      
      if (node.body.type === 'BlockExpr') {
        const block = node.body as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        if (last) {
          const lastExpr = this.transpileExpr(last);
          this.writeln(`return ${lastExpr};`);
        }
      } else {
        const body = this.transpileExpr(node.body);
        this.writeln(`return ${body};`);
      }
      
      this.indent--;
      this.writeln('}');
    } else {
      const params = node.params.map(p => p.name).join(', ');
      this.writeln(`${visibility}${asyncPrefix}function ${node.name}(${params}) {`);
      this.indent++;
      
      if (node.body.type === 'BlockExpr') {
        const block = node.body as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        if (last) {
          const lastExpr = this.transpileExpr(last);
          this.writeln(`return ${lastExpr};`);
        }
      } else {
        const body = this.transpileExpr(node.body);
        this.writeln(`return ${body};`);
      }
      
      this.indent--;
      this.writeln('}');
    }
    this.writeln();
  }

  private transpileLetDecl(node: LetDecl): void {
    if (node.pattern.type === 'ListPattern') {
      const value = this.transpileExpr(node.value);
      const tempValue = `__list_value_${this.instanceCounter++}`;
      this.writeln(`const ${tempValue} = ${value};`);
      const { condition, bindings, refs } = this.transpileListPatternMatch(node.pattern, tempValue);
      const checks = condition || 'true';
      this.writeln(`if (!(${checks})) { throw new Error('List pattern match failed'); }`);
      const allBindings = [refs, bindings].filter(Boolean).join('; ');
      if (allBindings) {
        this.writeln(`${allBindings};`);
      }
      return;
    }

    const keyword = node.isMutable ? 'let' : 'const';
    const pattern = this.transpileLetPattern(node.pattern);
    const value = this.transpileExpr(node.value);
    this.writeln(`${keyword} ${pattern} = ${value};`);
  }

  private transpileLetPattern(pattern: Pattern): string {
    switch (pattern.type) {
      case 'WildcardPattern':
        return '_';
      case 'IdentifierPattern':
        return pattern.as || pattern.name;
      case 'LiteralPattern':
        return this.transpileExpr(pattern.literal);
      case 'RecordPattern':
        return `{ ${pattern.fields.map(f => {
          const varName = f.pattern.type === 'IdentifierPattern' 
            ? (f.pattern as any).as || f.pattern.name 
            : this.transpileLetPattern(f.pattern);
          const defaultPart = f.defaultValue ? ` ?? ${this.transpileExpr(f.defaultValue)}` : '';
          return `${f.key}: ${varName}${defaultPart}`;
        }).join(', ')} }`;
      case 'TuplePattern':
        return `[${pattern.elements.map(e => this.transpileLetPattern(e)).join(', ')}]`;
      case 'ListPattern': {
        return '_';
      }
      case 'ConstructorPattern':
        const args = pattern.patterns.map(p => this.transpileLetPattern(p)).join(', ');
        return `${pattern.name}(${args})`;
      default:
        return '_';
    }
  }

  private transpilePattern(pattern: Pattern): string {
    switch (pattern.type) {
      case 'WildcardPattern':
        return '_';
      case 'IdentifierPattern':
        return pattern.as || pattern.name;
      case 'LiteralPattern':
        return this.transpileExpr(pattern.literal);
      case 'RecordPattern':
        return `{ ${pattern.fields.map(f => {
          const value = this.transpilePattern(f.pattern);
          return `${f.key}: ${value}`;
        }).join(', ')} }`;
      case 'TuplePattern':
        return `[${pattern.elements.map(e => this.transpilePattern(e)).join(', ')}]`;
      case 'ListPattern':
        return `[${pattern.elements.map(e => this.transpilePattern(e)).join(', ')}]`;
      case 'ConstructorPattern':
        const args = pattern.patterns.map(p => this.transpilePattern(p)).join(', ');
        return `${pattern.name}(${args})`;
      default:
        return '_';
    }
  }

  private transpileTypeDecl(node: TypeDecl): void {
    this.exports.push(node.name);
    
    if (node.recordFields) {
      const fields = node.recordFields.map(f => {
        const defaultPart = f.default ? ` = ${this.transpileExpr(f.default)}` : '';
        return `${f.name}: ${this.transpileType(f.fieldType)}${defaultPart}`;
      }).join(', ');
      this.writeln(`const ${node.name} = { ${fields} };`);
    } else {
      this.needsRuntime = true;
      
      const variants: Record<string, string[]> = {};
      for (const variant of node.variants) {
        const fieldNames = variant.fields.map(f => f.name);
        variants[variant.name] = fieldNames;
        this.constructors.set(variant.name, `${node.name}.${variant.name}`);
        this.variantFieldNames.set(variant.name, fieldNames);
        this.exports.push(variant.name);
      }
      
      const variantsStr = JSON.stringify(variants)
        .replace(/"/g, "'")
        .replace(/'([^']+)':/g, '$1:');
      
      this.writeln(`const ${node.name} = createADT('${node.name}', ${variantsStr});`);
      
      for (const variant of node.variants) {
        this.writeln(`const ${variant.name} = ${node.name}.${variant.name};`);
      }
    }
    this.writeln();
  }

  private transpileType(node: Node): string {
    if (node.type === 'Identifier') {
      return (node as Identifier).name;
    }
    if (node.type === 'CallExpr') {
      const call = node as CallExpr;
      const args = call.args.map(a => this.transpileType(a)).join(', ');
      return `${this.transpileExpr(call.callee)}<${args}>`;
    }
    return 'any';
  }

  private transpileImportStmt(node: ImportStmt): void {
    const moduleNameLower = node.module.toLowerCase();
    const namespace = this.getImportNamespace(node);

    if (STDLIB_MODULES.includes(moduleNameLower)) {
      const jsPath = `./${moduleNameLower}.js`;
      const moduleInfo = this.moduleInfoMap.get(node.module);

      if (node.implicit) {
        this.pushEsmImport(`import * as ${namespace} from '${jsPath}';`);
        const exportItems = (moduleInfo?.exports || []).filter(item => !this.isGeneratedDispatchMethod(item));
        for (const item of exportItems) {
          if (!this.importedNames.has(item)) {
            this.importedNames.set(item, namespace);
          }
        }
        return;
      }

      if (node.alias) {
        this.pushEsmImport(`import * as ${namespace} from '${jsPath}';`);
        this.importedNames.set(namespace, namespace);
        this.constructors.set(namespace, namespace);
        return;
      }

      // Keep a namespace import available for cross-module typeclass dispatch.
      this.pushEsmImport(`import * as ${namespace} from '${jsPath}';`);

      let importItems = moduleInfo?.exports ? [...moduleInfo.exports] : [];

      if (node.items && node.items.length > 0) {
        importItems = [...node.items];
      }

      if (node.hiding && node.hiding.length > 0) {
        importItems = importItems.filter(item => !node.hiding!.includes(item));
      }

      importItems = importItems.filter(item => !this.isGeneratedDispatchMethod(item));

      if (importItems.length > 0) {
        const itemsStr = importItems.join(', ');
        this.pushEsmImport(`import { ${itemsStr} } from '${jsPath}';`);
        for (const item of importItems) {
          this.importedNames.set(item, '');
          this.constructors.set(item, item);
        }
      } else {
        this.pushEsmImport(`import * as ${namespace} from '${jsPath}';`);
      }
      return;
    }

    this.needsRuntime = true;
    
    const jsPath = this.moduleToJsPath(node.module, node.isRelative);
    
    const moduleName = this.getModuleName(node.module);
    const sanitizedAlias = this.sanitizeModuleName(node.alias || moduleName);
    
    if (node.items && node.items.length > 0) {
      const itemsStr = node.items.join(', ');
      this.pushEsmImport(`import { ${itemsStr} } from '${jsPath}';`);
      for (const item of node.items) {
        this.importedNames.set(item, '');
        this.constructors.set(item, item);
      }
    } else if (node.alias) {
      this.pushEsmImport(`import * as ${sanitizedAlias} from '${jsPath}';`);
      this.importedNames.set(sanitizedAlias, sanitizedAlias);
      this.constructors.set(sanitizedAlias, sanitizedAlias);
    } else {
      this.pushEsmImport(`import * as ${sanitizedAlias} from '${jsPath}';`);
      
      const moduleKey = node.isRelative ? node.module : this.getModuleName(node.module);
      const moduleInfo = this.moduleInfoMap.get(node.module) || this.moduleInfoMap.get(moduleKey);
      
      if (moduleInfo) {
        for (const exportedName of moduleInfo.exports) {
          // Don't override locally defined dispatch functions
          if (!this.importedNames.has(exportedName)) {
            this.importedNames.set(exportedName, sanitizedAlias);
          }
        }
      }
    }
  }

  private registerImportNamespace(node: ImportStmt): void {
    const moduleNameLower = node.module.toLowerCase();
    const isStdlibModule = STDLIB_MODULES.includes(moduleNameLower);
    if (!isStdlibModule) {
      return;
    }

    const namespace = node.alias
      ? this.sanitizeModuleName(node.alias)
      : `__mod_${this.sanitizeModuleName(moduleNameLower)}`;
    this.moduleNamespaces.set(moduleNameLower, namespace);
    this.moduleNamespaces.set(node.module, namespace);
  }

  private getImportNamespace(node: ImportStmt): string {
    const moduleNameLower = node.module.toLowerCase();
    const existing = this.moduleNamespaces.get(node.module) || this.moduleNamespaces.get(moduleNameLower);
    if (existing) {
      return existing;
    }
    const fallback = node.alias
      ? this.sanitizeModuleName(node.alias)
      : `__mod_${this.sanitizeModuleName(moduleNameLower)}`;
    this.moduleNamespaces.set(moduleNameLower, fallback);
    this.moduleNamespaces.set(node.module, fallback);
    return fallback;
  }

  private pushEsmImport(importLine: string): void {
    if (!this.esmImports.includes(importLine)) {
      this.esmImports.push(importLine);
    }
  }

  private getImplicitStdlibImports(explicitImports: ImportStmt[]): ImportStmt[] {
    if (!this.currentFilePath || this.isStdlibSourceFile(this.currentFilePath)) {
      return [];
    }

    const explicitStdlibModules = new Set(
      explicitImports
        .map(imp => imp.module.toLowerCase())
        .filter(moduleName => STDLIB_MODULES.includes(moduleName))
    );

    return STDLIB_MODULES
      .filter(moduleName => !explicitStdlibModules.has(moduleName))
      .map(moduleName => ({
        type: 'ImportStmt',
        module: moduleName,
        isRelative: false,
        implicit: true,
      }));
  }

  private isStdlibSourceFile(filePath: string): boolean {
    return /[\\/]stdlib[\\/]/.test(filePath);
  }

  private getModuleName(modulePath: string): string {
    const parts = modulePath.split('/');
    return parts[parts.length - 1];
  }

  private sanitizeModuleName(moduleName: string): string {
    // Replace hyphens and other non-identifier characters with underscores
    return moduleName.replace(/[-\s.]/g, '_');
  }

  private moduleToJsPath(module: string, isRelative: boolean): string {
    if (isRelative) {
      // Relative import: ./foo-bar or ../foo-bar (module already includes ./ or ../)
      return `${module}.js`;
    } else {
      // Local import: foo-bar -> ./foo-bar.js
      return `./${module}.js`;
    }
  }

  private transpileExpr(node: Node): string {
    if (!node) {
      console.error('Error: transpileExpr called with undefined node');
      throw new Error('transpileExpr called with undefined node');
    }
    switch (node.type) {
      case 'NumberLiteral':
        return String((node as NumberLiteral).value);
      
      case 'StringLiteral':
        const str = (node as StringLiteral).value.replace(/"/g, '\\"');
        return `"${str}"`;
      
      case 'BooleanLiteral':
        return String((node as BooleanLiteral).value);
      
      case 'NoneLiteral':
        return 'null';
      
      case 'Identifier': {
        const name = (node as Identifier).name;
        const fullName = this.constructors.get(name);
        if (fullName) {
          const fieldNames = this.variantFieldNames.get(name);
          if (fieldNames && fieldNames.length === 0) {
            return `${fullName}()`;
          }
          return fullName;
        }
        
        const namespace = this.importedNames.get(name);
        if (namespace) {
          return namespace ? `${namespace}.${name}` : name;
        }

        if (name === 'Nil') {
          return '__listNil';
        }
        if (name === 'Cons') {
          return '__listCons';
        }
        
        return name;
      }
      
      case 'BinaryExpr': {
        const bin = node as BinaryExpr;
        const left = this.transpileExpr(bin.left);
        const right = this.transpileExpr(bin.right);

        if (bin.operator === '$') {
          return `${left}(${right})`;
        }
        if (bin.operator === '.') {
          return `((..._args) => ${left}(${right}(..._args)))`;
        }
        
        if (bin.operator === '||') {
          return `(${left} || ${right})`;
        }
        if (bin.operator === '&&') {
          return `(${left} && ${right})`;
        }
        if (bin.operator === '==') {
          return `(${left} === ${right})`;
        }
        if (bin.operator === '!=') {
          return `(${left} !== ${right})`;
        }
        if (bin.operator === '++') {
          return `(${left} + ${right})`;
        }
        return `(${left} ${bin.operator} ${right})`;
      }
      
      case 'UnaryExpr': {
        const unary = node as UnaryExpr;
        const operand = this.transpileExpr(unary.operand);
        return `${unary.operator}${operand}`;
      }
      
      case 'IndexExpr': {
        const index = node as IndexExpr;
        const object = this.transpileExpr(index.object);
        const idx = this.transpileExpr(index.index);
        return `${object}.get(${idx})`;
      }
      
      case 'MemberExpr': {
        const member = node as MemberExpr;
        const object = this.transpileExpr(member.object);
        const property = (member.property as Identifier).name;
        return `${object}.${property}`;
      }
      
      case 'CallExpr': {
        const call = node as CallExpr;
        let calleeStr = this.transpileExpr(call.callee);
        let isPrintCall = false;
        
        // Detect print() usage and mark runtime as needed
        if (call.callee.type === 'Identifier') {
          const funcName = (call.callee as Identifier).name;
          if (funcName === 'print') {
            this.needsRuntime = true;
            isPrintCall = true;
          }
        }
        
        if (call.callee.type === 'MemberExpr' && call.args.length === 0) {
          return `${calleeStr}()`;
        }
        if (call.args.length === 0) {
          return `${calleeStr}()`;
        }
        
        const args = call.args.map(a => this.transpileExpr(a)).join(', ');
        const argCount = call.args.length;

        if (isPrintCall && call.args.length === 1 && this.isShowAvailable()) {
          return `${calleeStr}(show(${args}))`;
        }
        
        // Check for currying: if calling a known function with fewer args than params
        if (call.callee.type === 'Identifier') {
          const funcName = (call.callee as Identifier).name;
          const paramCount = this.functions.get(funcName);
          if (paramCount !== undefined && argCount < paramCount) {
            // Generate curried function: (_c1) => (_c2) => fn(arg1, _c1, _c2)
            let result = '';
            for (let i = argCount; i < paramCount; i++) {
              result += `(_c${i}) => `;
            }
            result += `${calleeStr}(${args}`;
            for (let i = argCount; i < paramCount; i++) {
              result += `, _c${i}`;
            }
            result += ')';
            return result;
          }
        }
        
        // Wrap arrow functions in parentheses when called (for precedence)
        if (calleeStr.startsWith('(') && calleeStr.includes('=>')) {
          calleeStr = `(${calleeStr})`;
        }
        
        return `${calleeStr}(${args})`;
      }
      
      case 'FunctionExpr': {
        const fn = node as FunctionExpr;
        const params = fn.params.map(p => p.name).join(', ');
        const body = this.transpileExpr(fn.body);
        const getOperator = (op: string) => op === '++' ? '+' : op;
        if (fn.params.length === 1 && fn.params[0].name === '_left' && fn.body.type === 'BinaryExpr') {
          const bin = fn.body as BinaryExpr;
          if (bin.left.type === 'Identifier' && (bin.left as Identifier).name === '_left') {
            const op = getOperator(bin.operator);
            const right = this.transpileExpr(bin.right);
            return `(_left) => (_left ${op} ${right})`;
          }
          if (bin.right.type === 'Identifier' && (bin.right as Identifier).name === '_left') {
            const op = getOperator(bin.operator);
            const left = this.transpileExpr(bin.left);
            return `(_right) => (${left} ${op} _right)`;
          }
        }
        if (fn.params.length === 2 && fn.params[0].name === '_left' && fn.params[1].name === '_right' && fn.body.type === 'BinaryExpr') {
          const bin = fn.body as BinaryExpr;
          const left = this.transpileExpr(bin.left);
          const right = this.transpileExpr(bin.right);
          const op = getOperator(bin.operator);
          return `(_left, _right) => (_left ${op} _right)`;
        }
        return `(${params}) => ${body}`;
      }
      
      case 'IfExpr': {
        const ifExpr = node as IfExpr;
        const condition = this.transpileExpr(ifExpr.condition);
        const thenBranch = this.transpileExpr(ifExpr.thenBranch);
        const elseBranch = this.transpileExpr(ifExpr.elseBranch);
        return `((${condition}) ? ${thenBranch} : ${elseBranch})`;
      }
      
      case 'MatchExpr': {
        const match = node as MatchExpr;
        return this.transpileMatchExpr(match);
      }
      
      case 'RecordLiteral': {
        const record = node as RecordLiteral;
        const fields = record.fields.map(f => 
          `${f.key}: ${this.transpileExpr(f.value)}`
        ).join(', ');
        return `{ ${fields} }`;
      }
      
      case 'ListLiteral': {
        const list = node as ListLiteral;
        return this.buildListLiteral(list.elements);
      }
      
      case 'TupleLiteral': {
        const tuple = node as TupleLiteral;
        const elements = tuple.elements.map(e => this.transpileExpr(e)).join(', ');
        return `[${elements}]`;
      }
      
      case 'PipeExpr': {
        const pipe = node as PipeExpr;
        return this.transpilePipeExpr(pipe);
      }
      
      case 'BlockExpr': {
        const block = node as BlockExpr;
        const statements = block.body.slice(0, -1);
        const last = block.body[block.body.length - 1];
        for (const stmt of statements) {
          this.transpileNode(stmt);
        }
        return this.transpileExpr(last);
      }

      case 'ReturnExpr': {
        const ret = node as ReturnExpr;
        if (ret.value) {
          return `return ${this.transpileExpr(ret.value)}`;
        }
        return 'return';
      }
      
      case 'AwaitExpr': {
        const awaitExpr = node as AwaitExpr;
        const expr = this.transpileExpr(awaitExpr.expression);
        return `await ${expr}`;
      }
      
      case 'ForExpr': {
        const forExpr = node as ForExpr;
        const pattern = this.transpilePattern(forExpr.pattern);
        const iterable = this.transpileExpr(forExpr.iterable);
        const body = this.transpileExpr(forExpr.body);
        let loopCode = `for (const ${pattern} of ${iterable}) {\n`;
        this.indent++;
        if (forExpr.condition) {
          const condition = this.transpileExpr(forExpr.condition);
          loopCode += this.getIndent() + `if (!(${condition})) continue;\n`;
        }
        loopCode += this.getIndent() + body;
        this.indent--;
        loopCode += `\n${this.getIndent()}}`;
        return loopCode;
      }
      
      case 'WhileExpr': {
        const whileExpr = node as WhileExpr;
        const condition = this.transpileExpr(whileExpr.condition);
        const body = this.transpileExpr(whileExpr.body);
        let loopCode = `while (${condition}) {\n`;
        this.indent++;
        loopCode += this.getIndent() + body;
        this.indent--;
        loopCode += `\n${this.getIndent()}}`;
        return loopCode;
      }
      
      case 'BreakExpr': {
        return 'break';
      }
      
      case 'ContinueExpr': {
        return 'continue';
      }
      
      case 'ListComprehension': {
        const comp = node as ListComprehension;
        const element = this.transpileExpr(comp.element);
        const iterable = this.transpileExpr(comp.iterable);
        const { condition, bindings, refs } = this.transpileMatchPattern(comp.pattern, '__head');
        const guardParts: string[] = [];
        if (condition) {
          guardParts.push(`(${condition})`);
        }
        if (comp.condition) {
          guardParts.push(`(${this.transpileExpr(comp.condition)})`);
        }
        const guard = guardParts.length > 0 ? guardParts.join(' && ') : 'true';
        const allBindings = [refs, bindings].filter(Boolean).join('; ');
        const bindingBlock = allBindings ? `${allBindings}; ` : '';
        return `((__list) => { const __go = (__xs) => { if (!(__xs && __xs._variant === 'Cons')) { return __listNil; } const __head = __xs.head; const __tail = __xs.tail; ${bindingBlock}if (${guard}) { return __listCons(${element}, __go(__tail)); } return __go(__tail); }; return __go(__list); })(${iterable})`;
      }
      
      case 'StringInterpolation': {
        const interp = node as StringInterpolation;
        let result = '`';
        for (const part of interp.parts) {
          if (part.type === 'StringPart') {
            result += (part as any).value;
          } else if (part.type === 'ExprPart') {
            const expr = this.transpileExpr((part as any).expr);
            result += `\${${expr}}`;
          }
        }
        result += '`';
        return result;
      }
      
      default:
        return 'undefined';
    }
  }

  private transpileMatchExpr(match: MatchExpr): string {
    const value = this.transpileExpr(match.value);
    const cases = match.arms.map(arm => {
      const { bindings, condition, refs } = this.transpileMatchPattern(arm.pattern);
      const body = this.transpileExpr(arm.body);
      let guardCondition = condition;
      if (arm.guard) {
        const guard = this.transpileExpr(arm.guard.condition);
        guardCondition = guardCondition ? `(${guardCondition} && ${guard})` : guard;
      }
      return { bindings, condition: guardCondition, body, refs };
    });

    let result = `((__v) => {\n`;
    for (const c of cases) {
      let refs = c.refs;
      if (refs.endsWith('; ')) refs = refs.slice(0, -2);
      else if (refs.endsWith(';')) refs = refs.slice(0, -1);
      const allBindings = [refs, c.bindings].filter(b => b).join('; ');
      if (c.condition) {
        result += `  { ${allBindings}${allBindings ? '; ' : ''}if (${c.condition}) { return ${c.body}; } }\n`;
      } else {
        result += `  { ${allBindings}${allBindings ? '; ' : ''}return ${c.body}; }\n`;
      }
    }
    result += `})(${value})`;
    return result;
  }

  private transpileMatchPattern(pattern: Pattern, value: string = '__v'): { bindings: string; condition: string; refs: string } {
    switch (pattern.type) {
      case 'WildcardPattern':
        return { bindings: '', condition: '', refs: '' };
      case 'IdentifierPattern':
        return { bindings: '', condition: '', refs: `const ${pattern.name} = ${value}` };
      case 'LiteralPattern':
        return { bindings: '', condition: `${value} === ${this.transpileExpr(pattern.literal)}`, refs: '' };
      case 'RecordPattern': {
        const conds: string[] = [];
        const binds: string[] = [];
        const refs: string[] = [];
        for (const f of pattern.fields) {
          const fieldValue = `${value}.${f.key}`;
          const result = this.transpileMatchPattern(f.pattern, fieldValue);
          if (result.condition) conds.push(result.condition);
          if (result.bindings) binds.push(result.bindings);
          if (result.refs) refs.push(result.refs);
        }
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join(' ') };
      }
      case 'ListPattern': {
        return this.transpileListPatternMatch(pattern, value);
      }
      case 'TuplePattern': {
        const elems = pattern.elements.map((e, i) => this.transpileMatchPattern(e, `${value}[${i}]`));
        const conds = elems.map(e => e.condition).filter(c => c);
        const binds = elems.map(e => e.bindings).filter(b => b);
        const refs = elems.map(e => e.refs).filter(r => r);
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join(' ') };
      }
      case 'ConstructorPattern': {
        // Always use _variant for ADT pattern matching (built-in and custom)
        const conds = [`${value}._variant === '${pattern.name}'`];
        const binds: string[] = [];
        const refs: string[] = [];
        const fieldNames = this.getVariantFieldNames(pattern.name);
        pattern.patterns.forEach((p, i) => {
          const fieldName = fieldNames[i] || `v${i}`;
          if (p.type === 'IdentifierPattern') {
            const bindName = (p as any).name;
            refs.push(`const ${bindName} = ${value}.${fieldName}`);
          } else {
            const result = this.transpileMatchPattern(p, `${value}.${fieldName}`);
            if (result.condition) conds.push(result.condition);
            if (result.bindings) binds.push(result.bindings);
            if (result.refs) refs.push(result.refs);
          }
        });
        return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join('; ') };
      }
      default:
        return { bindings: '', condition: '', refs: '' };
    }
  }

  private transpileListPatternMatch(
    pattern: Extract<Pattern, { type: 'ListPattern' }>,
    value: string
  ): { bindings: string; condition: string; refs: string } {
    const conds: string[] = [];
    const binds: string[] = [];
    const refs: string[] = [];

    let current = value;
    pattern.elements.forEach((elemPattern) => {
      conds.push(`${current} && ${current}._variant === 'Cons'`);
      const elem = this.transpileMatchPattern(elemPattern, `${current}.head`);
      if (elem.condition) conds.push(elem.condition);
      if (elem.bindings) binds.push(elem.bindings);
      if (elem.refs) refs.push(elem.refs);
      current = `${current}.tail`;
    });

    if (pattern.rest) {
      refs.push(`const ${pattern.rest} = ${current}`);
    } else {
      conds.push(`${current} && ${current}._variant === 'Nil'`);
    }

    return { bindings: binds.join(' '), condition: conds.join(' && '), refs: refs.join('; ') };
  }

  private buildListLiteral(elements: Node[]): string {
    let result = '__listNil';
    for (let i = elements.length - 1; i >= 0; i--) {
      result = `__listCons(${this.transpileExpr(elements[i])}, ${result})`;
    }
    return result;
  }

  private emitListHelpers(): void {
    this.writeln('const __listIterator = function* (start) {');
    this.indent++;
    this.writeln('let current = start;');
    this.writeln('while (current && current._variant === "Cons") {');
    this.indent++;
    this.writeln('yield current.head;');
    this.writeln('current = current.tail;');
    this.indent--;
    this.writeln('}');
    this.indent--;
    this.writeln('};');
    this.writeln('const __listNil = Object.freeze({');
    this.indent++;
    this.writeln('_type: "List",');
    this.writeln('_variant: "Nil",');
    this.writeln('_values: [],');
    this.writeln('[Symbol.iterator]: function* () { }');
    this.indent--;
    this.writeln('});');
    this.writeln('const __listCons = (head, tail) => Object.freeze({');
    this.indent++;
    this.writeln('_type: "List",');
    this.writeln('_variant: "Cons",');
    this.writeln('_values: [head, tail],');
    this.writeln('head,');
    this.writeln('tail,');
    this.writeln('[Symbol.iterator]: function* () { yield* __listIterator(this); }');
    this.indent--;
    this.writeln('});');
    this.writeln('');
  }

  private getVariantFieldNames(typeName: string): string[] {
    // Check if this is a custom ADT variant first
    if (this.variantFieldNames.has(typeName)) {
      return this.variantFieldNames.get(typeName) || [];
    }
    
    const fieldMap: Record<string, string[]> = {
      'Circle': ['r'],
      'Rectangle': ['width', 'height'],
      'Ok': ['value'],
      'Err': ['error'],
      'Some': ['value'],
      'Just': ['value'],
      'Nothing': [],
      'Cons': ['head', 'tail'],
      'Nil': [],
    };
    return fieldMap[typeName] || [];
  }

  private getIndent(): string {
    return '  '.repeat(this.indent);
  }

  private transpilePipeExpr(pipe: PipeExpr): string {
    const left = this.transpileExpr(pipe.left);
    const right = pipe.right;
    
    if (right.type === 'CallExpr') {
      const call = right as CallExpr;
      const callee = this.transpileExpr(call.callee);
      const existingArgs = call.args.map(a => this.transpileExpr(a)).join(', ');
      const args = existingArgs ? `${existingArgs}, ${left}` : left;
      return `${callee}(${args})`;
    }
    
    const rightStr = this.transpileExpr(right);
    return `${rightStr}(${left})`;
  }

  private transpileTypeclassDecl(node: TypeclassDecl): void {
    this.exports.push(node.name);
    
    // Generate default implementations for methods with bodies
    for (const method of node.methods) {
      if (method.body) {
        // Generate a default implementation function
        const defaultFnName = `__default_${node.name}_${method.name}`;
        const paramList = method.params.map(p => p.name).join(', ');
        this.writeln(`const ${defaultFnName} = function(${paramList}) {`);
        this.indent++;
        const methodBody = this.transpileExpr(method.body);
        this.writeln(`return ${methodBody};`);
        this.indent--;
        this.writeln('};');
        // Export default implementations so they can be used by impl in other files
        this.exports.push(defaultFnName);
      }
    }
    
    // Typeclasses are just type declarations at transpile time
    // The actual method dispatch happens at runtime via the constraint registry
    // Generate a const that represents the typeclass interface
    this.writeln(`const ${node.name} = {`);
    this.indent++;
    
    for (const method of node.methods) {
      if (method.body) {
        this.writeln(`${method.name}: __default_${node.name}_${method.name},`);
      } else {
        this.writeln(`${method.name}: null, // Will be filled by instances`);
      }
    }
    
    this.indent--;
    this.writeln('};');
    this.writeln();
  }

  private transpileInstanceDecl(node: InstanceDecl): void {
    // Generate the instance implementation object
    // For Convertible for (Int, String), we generate something like:
    // registerInstance('Convertible', ['Int', 'String'], { convert: (x) => x.toString() });
    
    const forTypesStr = node.forTypes.length === 1 
      ? this.transpileExpr(node.forTypes[0])
      : `[${node.forTypes.map(t => this.transpileExpr(t)).join(', ')}]`;
    
    this.writeln(`// Instance: ${node.typeclass} for ${forTypesStr}`);
    
    // Get the pre-calculated instance variable names from first pass
    const allInstanceIds = this.instanceIds.get(node.typeclass) || [];
    // Count how many instances of this typeclass we've already processed
    let processedCount = 0;
    if (!this.constructors.has(`__processed_instances_${node.typeclass}`)) {
      this.constructors.set(`__processed_instances_${node.typeclass}`, '0');
    }
    processedCount = parseInt(this.constructors.get(`__processed_instances_${node.typeclass}`) || '0');
    
    let instanceVarName = allInstanceIds[processedCount] || `__instance_${node.typeclass}_${processedCount}`;
    this.constructors.set(`__processed_instances_${node.typeclass}`, String(processedCount + 1));
    
    // Get the typeclass to check for default implementations
    const typeclass = this.typeclasses.get(node.typeclass);
    const implementedMethods = new Set(node.methods.map(m => m.name));
    
    // Generate an object with all the methods (implementing + defaults)
    this.writeln(`const ${instanceVarName} = {`);
    this.indent++;
    
    // First, add the implemented methods
    for (const method of node.methods) {
      // Use parameter names from the implementation if available, otherwise from typeclass
      let paramList = 'x';
      if (method.params && method.params.length > 0) {
        paramList = method.params.join(', ');
      } else if (typeclass) {
        const tcMethod = typeclass.methods.find(m => m.name === method.name);
        if (tcMethod && tcMethod.params.length > 0) {
          paramList = tcMethod.params.map(p => p.name || 'arg').join(', ');
        }
      }
      
      const methodBody = this.transpileExpr(method.body);
      this.writeln(`${method.name}: function(${paramList}) { return ${methodBody}; },`);
    }
    
    // Then, add default implementations from the typeclass for methods not implemented
    if (typeclass) {
      for (const method of typeclass.methods) {
        if (!implementedMethods.has(method.name) && method.body) {
          // Try to use the exported default function, otherwise generate inline
          const defaultFnName = `__default_${node.typeclass}_${method.name}`;
          const paramNames = method.params.map(p => p.name || 'arg');
          const paramList = paramNames.join(', ');
          
          // Generate inline function for default implementation
          const methodBody = this.transpileExpr(method.body);
          this.writeln(`${method.name}: function(${paramList}) { return ${methodBody}; },`);
        }
      }
    }
    
    this.indent--;
    this.writeln('};');
    this.writeln();
  }

  private getTypeName(typeNode: Node | any): string {
    if (typeof typeNode === 'string') {
      return typeNode;
    }
    if (typeNode.type === 'Identifier') {
      return typeNode.name;
    }
    if (typeNode.type === 'GenericType') {
      return typeNode.name; // Return base name like 'List' from 'List(a)'
    }
    if (typeNode.type === 'CallExpr' && typeNode.callee && typeNode.callee.type === 'Identifier') {
      return typeNode.callee.name; // Return 'List' from List(a)
    }
    return 'unknown';
  }

  private isShowAvailable(): boolean {
    return this.importedNames.has('show') || this.functions.has('show');
  }

  private isGeneratedDispatchMethod(name: string): boolean {
    for (const [, typeclassDecl] of this.typeclasses) {
      if (typeclassDecl.methods.some(method => method.name === name)) {
        return true;
      }
    }
    return false;
  }

  private generateDispatchFunctions(): void {
    // Generate dispatch functions for each typeclass method
    for (const [tcName, tc] of this.typeclasses) {
      const instanceVarNames = this.instanceIds.get(tcName) || [];
      const externalInstances = this.globalInstances.filter(inst =>
        inst.typeclass === tcName &&
        inst.methods.includes(tc.methods[0]?.name || '')
      );
      
      if (instanceVarNames.length === 0 && externalInstances.length === 0) {
        // No instances for this typeclass - skip dispatch generation
        continue;
      }

      // For each method in the typeclass, create a dispatch function
      for (const method of tc.methods) {
        const methodName = method.name;

        // Keep an existing top-level function when a module defines one with the same name.
        if (this.functions.has(methodName)) {
          continue;
        }
        
        // Register this method name as a local function (empty string means no namespace)
        this.importedNames.set(methodName, '');

        if (!this.exports.includes(methodName)) {
          this.exports.push(methodName);
        }
        
        // Extract parameter names from the method signature
        const paramNames = method.params.map(p => {
          if (p.name) return p.name;
          return 'arg';
        });
        const paramList = paramNames.join(', ');
        
        this.writeln(`// Dispatch function for ${tcName}.${methodName}`);
        this.writeln(`const ${methodName} = (${paramList}) => {`);
        this.indent++;
        
        // Try each instance in order with type checking
        for (const instanceVarName of instanceVarNames) {
          const typeNames = this.instanceTypes.get(instanceVarName) || [];
          const typeCheck = this.generateTypeCheck(typeNames[0], paramNames[0] || 'x');
          
          this.writeln(`if (${typeCheck}) {`);
          this.indent++;
          this.writeln(`if (${instanceVarName}.${methodName}) {`);
          this.indent++;
          this.writeln(`return ${instanceVarName}.${methodName}(${paramList});`);
          this.indent--;
          this.writeln(`}`);
          this.indent--;
          this.writeln(`}`);
        }

        // Try imported module instances (cross-module dispatch).
        const externalInstances = this.globalInstances.filter(inst =>
          inst.typeclass === tcName &&
          inst.methods.includes(methodName)
        );
        for (const instance of externalInstances) {
          const moduleNamespace = this.moduleNamespaces.get(instance.module) || this.moduleNamespaces.get(instance.module.toLowerCase());
          if (!moduleNamespace) {
            continue;
          }
          const typeCheck = this.generateTypeCheck(instance.forTypes[0], paramNames[0] || 'x');
          this.writeln(`if (${typeCheck}) {`);
          this.indent++;
          this.writeln(`if (${moduleNamespace}.${methodName}) {`);
          this.indent++;
          this.writeln(`return ${moduleNamespace}.${methodName}(${paramList});`);
          this.indent--;
          this.writeln(`}`);
          this.indent--;
          this.writeln(`}`);
        }
        
        // Fallback: use default implementation if available
        if (method.body) {
          const defaultImpl = this.transpileExpr(method.body);
          this.writeln(`return ${defaultImpl};`);
        } else {
          this.writeln(`throw new Error('No instance of ${tcName} found for ' + typeof ${paramNames[0]});`);
        }
        
        this.indent--;
        this.writeln('};');
        this.writeln();
      }
    }
  }

  private generateTypeCheck(typeName: string | undefined, valueRef: string = 'x'): string {
    if (!typeName) return 'true';
    
    switch (typeName) {
      case 'Int':
        return `Number.isInteger(${valueRef})`;
      case 'String':
        return `typeof ${valueRef} === "string"`;
      case 'Boolean':
        return `typeof ${valueRef} === "boolean"`;
      case 'Float':
        return `typeof ${valueRef} === "number" && !Number.isInteger(${valueRef})`;
      case 'List':
        return `${valueRef} && ${valueRef}._type === 'List'`;
      default:
        return `${valueRef} && ${valueRef}._type === '${typeName}'`;
    }
  }
}

export function transpile(ast: Program): string {
  const transpiler = new Transpiler();
  return transpiler.transpile(ast);
}
